<a href="https://colab.research.google.com/github/kalyani1106/kalyani/blob/kalyani/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

List vs Numpy-Time taken

In [2]:
from time import process_time

In [5]:
my_list=[i for i in range(10000)]
start_time=process_time()
my_list=[i+5 for i in my_list]
end_time=process_time()
print(end_time-start_time)

0.0005728759999996669


In [6]:
np_array=np.array([i for i in range(10000)])
start_time=process_time()
np_array+=5
end_time=process_time()
print(end_time-start_time)

0.0002231600000008882


Numpy Arrays

In [7]:
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [10]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [13]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [14]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial placeholders

In [17]:
x=np.zeros((3,3))
print(x)
y=np.ones((3,3))
print(y)
z=np.full((3,3),5)
print(z)
u=np.eye(3)
print(u)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
a=np.random.random((3,4))
print(a)
b=np.random.randint(10,100,(3,4))
print(b)

[[0.6965788  0.67655472 0.18188256 0.55556096]
 [0.46611828 0.5608784  0.06388666 0.49916596]
 [0.68006034 0.72474099 0.48551582 0.17382279]]
[[49 52 53 51]
 [95 29 74 35]
 [85 47 21 10]]


In [21]:
c=np.linspace(10,30,5)
print(c)

[10. 15. 20. 25. 30.]


In [25]:
d=np.arange(0,31,5)
print(d)

[ 0  5 10 15 20 25 30]


In [26]:
list2=[1,2,3,4,5]
np_array=np.asarray(list2)
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [28]:
v=np.random.randint(10,100,(5,5))
print(v)

[[10 52 20 17 91]
 [80 46 79 49 21]
 [64 50 62 17 26]
 [57 59 65 11 30]
 [91 32 42 70 57]]


In [29]:
print(v.shape)

(5, 5)


In [30]:
print(v.ndim)

2


In [32]:
print(v.size)

25


In [34]:
print(v.dtype)

int64


**Mathematical operations**

In [35]:
a=np.random.randint(10,100,(3,3))
b=np.random.randint(10,100,(3,3))
print(a)
print(b)

[[43 39 88]
 [55 83 17]
 [54 72 72]]
[[62 32 17]
 [21 67 40]
 [98 77 93]]


In [38]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[105  71 105]
 [ 76 150  57]
 [152 149 165]]
[[-19   7  71]
 [ 34  16 -23]
 [-44  -5 -21]]
[[2666 1248 1496]
 [1155 5561  680]
 [5292 5544 6696]]
[[0.69354839 1.21875    5.17647059]
 [2.61904762 1.23880597 0.425     ]
 [0.55102041 0.93506494 0.77419355]]
[[105  71 105]
 [ 76 150  57]
 [152 149 165]]
[[-19   7  71]
 [ 34  16 -23]
 [-44  -5 -21]]
[[2666 1248 1496]
 [1155 5561  680]
 [5292 5544 6696]]
[[0.69354839 1.21875    5.17647059]
 [2.61904762 1.23880597 0.425     ]
 [0.55102041 0.93506494 0.77419355]]


In [39]:
trans=np.transpose(a)
print(trans)

[[43 55 54]
 [39 83 72]
 [88 17 72]]


In [40]:
trans2=a.T
print(trans2)

[[43 55 54]
 [39 83 72]
 [88 17 72]]


In [49]:
a=np.random.randint(10,100,(2,3))
print(a)
a.shape

[[26 23 33]
 [80 86 51]]


(2, 3)

In [48]:
b=a.reshape(3,2)
print(b)
b.shape

[[19 96]
 [43 18]
 [32 23]]


(3, 2)